AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

StringLiterals:
  EnforcedStyle: single_quotes

DotPosition:
  EnforcedStyle: leading

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false
