version: '2'
services:
  worker:
    build: .
    env_file: .env
    links:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  rabbitmq:
    image: rabbitmq:3.6.4-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
